/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package alluxio.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum TExceptionStatus implements org.apache.thrift.TEnum {
  Canceled(1),
  Unknown(2),
  InvalidArgument(3),
  DeadlineExceeded(4),
  NotFound(5),
  AlreadyExists(6),
  PermissionDenied(7),
  Unauthenticated(16),
  ResourceExhausted(8),
  FailedPrecondition(9),
  Aborted(10),
  OutOfRange(11),
  Unimplemented(12),
  Internal(13),
  Unavailable(14),
  DataLoss(15);

  private final int value;

  private TExceptionStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TExceptionStatus findByValue(int value) { 
    switch (value) {
      case 1:
        return Canceled;
      case 2:
        return Unknown;
      case 3:
        return InvalidArgument;
      case 4:
        return DeadlineExceeded;
      case 5:
        return NotFound;
      case 6:
        return AlreadyExists;
      case 7:
        return PermissionDenied;
      case 16:
        return Unauthenticated;
      case 8:
        return ResourceExhausted;
      case 9:
        return FailedPrecondition;
      case 10:
        return Aborted;
      case 11:
        return OutOfRange;
      case 12:
        return Unimplemented;
      case 13:
        return Internal;
      case 14:
        return Unavailable;
      case 15:
        return DataLoss;
      default:
        return null;
    }
  }
}
